### ISSUE TITLE
loading and reloading in IHaskell

### ISSUE THREAD

**Issue by krey** [gibiansky/IHaskell#1221]
Dear IHaskell team,

First of all, thanks for the awesome project.

I noticed that the `:load` (or `:l`) directive isn't documented on the [wiki](https://github.com/gibiansky/IHaskell/wiki). Could we add this?

It would also be worth mentioning the fact that it's not possible to reload modules at the moment (lack of `:r`) https://github.com/gibiansky/IHaskell/issues/946

Would it be possible to add reloading support?

Many thanks

**Comment by vaibhavsagar** [comment]
> Could we add this?

I had forgotten we had a wiki :sweat_smile:. The page you link to hasn't been updated since 2015. It also includes this line:

> Many of the directives are shared with GHCi for the sake of convenience, though they do not necessarily behave in the exact same ways.

I won't update the wiki page, as I don't want to create or contribute to the expectation that it is current, but I will look into documenting this in the output of `:help`.

> Would it be possible to add reloading support?

IHaskell is not GHCi, although there are some similarities. Reloading as provided by `:reload` makes a lot more sense in the context of GHCi than it does when using IHaskell, where you can just reload the whole notebook and pick up any changes in the process. What is your use case that requires this feature?

We usually implement features that are present in GHCi by adapting the relevant source from that codebase. It looks like the logic for reloading is [here](https://gitlab.haskell.org/ghc/ghc/-/blob/5e1a224435fc6ebd34d02566f17fe1eaf5475bab/ghc/GHCi/UI.hs#L2060-2065), if you want to port it then I will happily review and merge, but I have no need for this feature myself so I am unlikely to ever add it myself.

**Comment by krey** [comment]
Thanks for the fast response @vaibhavsagar 

Yes, I think adding it to `:help` would definitely be helpful.

> IHaskell is not GHCi, although there are some similarities. Reloading as provided by :reload makes a lot more sense in the context of GHCi than it does when using IHaskell, where you can just reload the whole notebook and pick up any changes in the process. What is your use case that requires this feature?

I don't see the difference between Notebooks and the REPL as clearly as you do. My use cases are the same for the two. Write some code in a `.hs` file, save, reload, run a few cells to test out the results...

>  looks like the logic for reloading is here, if you want to port it then I will happily review and merge

That's fair, thanks. I looked at the code linked and `Evaluate.hs` and it's way over my head. Reloading looks like a non-trivial feature to add...

**Comment by vaibhavsagar** [comment]
Is there a reason that reloading the whole notebook after making changes to your `.hs` file isn't sufficient for your purposes? You can do this with Jupyter but not the REPL, which I think is the main difference here.

**Comment by krey** [comment]
Restart & Run All tends to be significantly slower that a ghci reload. That's the main difference

**Comment by vaibhavsagar** [comment]
Hi, I was scared off implementing this by the GHCi source code but it turned we already had something very similar that it was possible to extend to support `:reload` too. I made a PR at https://github.com/gibiansky/IHaskell/pull/1237, can you try it and see if it fits your needs?

**Comment by vaibhavsagar** [comment]
Closing as the linked PR has been merged. Please reopen if needed.
