### ISSUE TITLE
Issue importing modules

### ISSUE THREAD

**Issue by odcameron** [gibiansky/IHaskell#1239]
I installed iHaskell on Linux following these instructions. I tried to do some simple data analysis with iHaskell, but after installation it wouldn't import really simple modules like Data.List.

`module Assignment2 where
import Data.List 
`
`x = [1,2,3]
delete 2 x
`
Brings up error 
"<interactive>:1:1: error: Variable not in scope: delete :: t0 -> [a0] -> t"

I conclude that it is not loading modules properly. Is this right? Seems like a bug.

**Comment by vaibhavsagar** [comment]
No, it's not a bug. When you write

```haskell
module Assignment2 where
import Data.List
```

it creates a module in the working directory called `Assignment2` with the contents you specified. If you want to use that module you need to then run

```haskell
import Assignment2
```

afterwards, but that doesn't give you access to `Data.List` since you haven't explicitly exported it in `Assignment2`. I'm guessing this isn't what you intended to do. If you only want to import `Data.List`, you can just do that:

```haskell
import Data.List
x = [1,2,3]
delete 2 x
```
