### ISSUE TITLE
mybinder not working

### ISSUE THREAD

**Issue by imba-tjd** [gibiansky/IHaskell#1278]
![image](https://user-images.githubusercontent.com/24759802/133350274-7599b6ae-3825-4588-827e-4ca09fbdf39c.png)

**Comment by vaibhavsagar** [comment]
I think this happened because mybinder.org switched to using JupyterLab instead of the Jupyter Notebook interface. It's fixed now but the original link probably won't work until the cache invalidates. In the meantime you can use https://mybinder.org/v2/gh/gibiansky/IHaskell/mybinder-tmp (which is a temporary branch I just created and will probably delete at some point in the future).
