### ISSUE TITLE
building with npm

### ISSUE THREAD

**Issue by mehmeh-ctrl** [gibiansky/IHaskell#1325]
I am slowly giving up on Haskell, iHaskell in Jupyter worked, then don't ... as usual

pm ERR! Linux 5.13.0-30-generic
npm ERR! argv "/home/ma/anaconda3/bin/node" "/home/ma/anaconda3/bin/npm" "run" "build"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! jupyterlab-ihaskell@0.0.14 build: `tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyterlab-ihaskell@0.0.14 build script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyterlab-ihaskell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterlab-ihaskell
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyterlab-ihaskell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ma/ihaskell-brew/IHaskell/jupyterlab-ihaskell/labextension/npm-debug.log

**Comment by vaibhavsagar** [comment]
I'm sorry you're having a difficult time with IHaskell, it is unfortunately a complicated bit of software to install because it involves wrangling the Haskell, Python, and Node dependencies simultaneously. I don't see why you need to use `jupyterlab-ihaskell` if you're using classic notebooks though (with `jupyter notebook`), and if you are sure you want JupyterLab we also provide [a prebuilt extension](https://github.com/gibiansky/IHaskell/tree/618a315bbd8b2def4928a72ef7024b7e5fbcbc39/jupyterlab-ihaskell/labextension) that can be copied to e.g. `~/.local/share/jupyter/labextensions/jupyterlab-ihaskell` so you don't have to build it yourself.

**Comment by mehmeh-ctrl** [comment]
Every rime I build Haskell I somehow succeed (every time I reinstall the system I do it, because it posses a challenge), I've seen the JupyterLab extension, I've used it sometime ago. This time stack install ihaskell was needed, it wasn't earlier.
