### ISSUE TITLE
Package IHaskell [$25]

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#205]
This is a while out, but it might be nice to package IHaskell nicely for end-users that aren't as experienced with Haskell.

Other ideas:
- Make a Docker build (https://github.com/gibiansky/IHaskell/issues/136) so that it is easy to install on any Linux distribution
- Package as Mac app (that can hang around in the task bar and have it's own window instead of using a browser, by having our own webview or something.)
- Package for windows like Sage does ([see here](http://www.sagemath.org/download-windows.html))
- Package for package managers?
 - Homebrew?
 - Debian's apt-get?

Not sure which of these are worthwhile, but might be a good effort to get IHaskell and Haskell out to a wider audience.

**Comment by gibiansky** [comment]
@houshuang Check out [Kronos Haskell](http://www.kronosnotebook.com/haskell).

**Comment by gibiansky** [comment]
@mietek I'm closing this issue as I meant it mostly for Kronos Haskell but I experimented a bit with BountySource so there's a $25 bounty on it. If you want to claim it please do so – your work on Halcyon is pretty awesome! (I came to the conclusion that I am not a big fan of BountySource... I do not like their model very much.)

Other issues with more specific requests can be opened – things like packaging for Windows via virtual machine, packaging for homebrew or apt-get, etc, are still valid and potentially desirable.

**Comment by mietek** [comment]
Thanks. As an update — [Instant IHaskell](https://github.com/mietek/instant-ihaskell) now supports one-click deployment to DigitalOcean instances running Ubuntu 14.04.  CentOS 7 is not fully supported yet, as a problem with `pango` prevents two IHaskell display modules from building.

My packaging should also allow IHaskell to be deployed to Heroku.  Unfortunately, the 1.6GB installation directory chokes Heroku’s internal distribution systems.  Hopefully, this will be fixed in the future, and everyone will be able to spin up their own IHaskell instances for free on Heroku.
