### ISSUE TITLE
Separate command to install profile/fill kernelspec directory.

### ISSUE THREAD

**Issue by Carreau** [gibiansky/IHaskell#321]
Right now this is done on starting IHaskell notebook once, but then you need to kill the server. 

It would be nice to have a separate command to just do that.

**Comment by gibiansky** [comment]
I hope that with the Jupyter/IPython 3 migration, the IHaskell interface / application will be completely gone.

You will have the following setup then:
1. Install Jupyter somehow yourself. That's up to you, and it's not IHaskell's problem.
2. `cabal install IHaskell` (along with installing any necessary dependencies)
3. Run `ihaskell setup` or `ihaskell setup --ipython-dir /path/to/ipython` or something to install the kernelspec. 

From then on Jupyter will handle everything.

Sadly I think this will involve losing some IHaskell features because Jupyter does not allow for everything IHaskell does (just 95% of it), but I think those are rarely used features anyways. The hassle of maintaining installation issues is too big and really bogs me down, so offloading all of that to Jupyter will encourage me to develop IHaskell further instead of getting bogged down in unpleasant installation woes.

**Comment by Carreau** [comment]
We should be in RC soon, so in a few weeks we can start re-adding feature and awesome ideas.
We will be happy to get inputs.

**Comment by gibiansky** [comment]
Oh, of course! I didn't mean to imply that it was necessarily a *permanent* change / loss of functionality – just that it is more important for me to rearchitect IHaskell into the Jupyter kernel style than keep every single feature it has accumulated.

The main few issues are with conversions between document formants. This is fairly rigid in IPython / Jupyter nowadays, but I suspect that's more due to lack of time / other priorities on the core dev team rather than any fundamental difficulties.

**Comment by Carreau** [comment]
Well, my little finger should get answers for fundings in April. Hopefully a little bit more that what we have today, which should expand our horizon a bit. 

I'm not in totally involved in the process, but depending on the result I guess some people might try to reach out to people involve in Jupyter-related project to get new blood and ideas.

**Comment by gibiansky** [comment]
Currently this is done with `ihaskell install`.
