### ISSUE TITLE
Adding a Show instance for a type results in problems

### ISSUE THREAD

**Issue by DougBurke** [gibiansky/IHaskell#367]
I'm not 100% convinced this is IHaskell related, but the evidence points that way. In goldfirere/units#46 I reported that adding a `Show` instance causes type inference problems from within IHaskell, which I had originally attributed to the `units` package. However, I don't see the problem if I use `ghci` instead of an IHaskell notebook, which makes me suspect the environment provided by IHaskell. Please see goldfirere/units#46 for full details, but the gist is that after defining a bunch of data types I can say, in `ghci`:

~~~~
ghci> 0.4 % Radian
0.4
ghci> instance Show Radian where show _ = "XXX"
ghci> 0.4 % Radian
0.4
~~~~

but in IHaskell, I get

~~~~
In [4]: 0.3 % Radian
          0.3
In [5]: instance Show Radian where show _ = "rad"
In [6]: 0.3 % Radian
Could not deduce (Unit Radian) arising from a use of ‘%’
from the context (Fractional n) bound by the inferred type of it :: Fractional n => Qu '[] 'DefaultLCSU n at :1:1-12
In the expression: 0.3 % Radian
In an equation for ‘it’: it = 0.3 % Radian
~~~~

This is on a Ubuntu 14.10 system with

~~~~
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4
% cabal sandbox hc-pkg list | grep -i ihaskell
    ihaskell-0.5.0.0
    ihaskell-blaze-0.2.0.0
~~~~

and I've placed a gist of the notebook at https://gist.github.com/DougBurke/c61cfaba15a97fdc6f10

**Comment by gibiansky** [comment]
I have recently fixed a bug related to instance declarations that caused some declarations to be ignored. 

Do you mind trying this again with `master` to see if it is still happening? I strongly suspect it should be fixed, but had difficulty getting that notebook working. (Note that `master` requires IPython 3.0, which can be installed via `pip`, as it was released last week)

**Comment by DougBurke** [comment]
I'll hopefully have some time to get to it this week-end, which almost-certainly dooms me!

**Comment by DougBurke** [comment]
I have managed to 'cabal install' master into a cabal sandbox, but it fails to run since - as you mention - I don't have IPython 3.0. I'm used to the "old" IHaskell behavior of it creating a virtualenv for me, but it looks like this logic has been removed. How can I setup/install IPython 3.0 here in a virtualenv-like environment to test out IHaskell (I'm not doing a pip install with my standard python installation)?

**Comment by gibiansky** [comment]
@DougBurke Yes, IHaskell now supports IPython 3.0 and up. you should be able to install IPython 3.0 in a virtualenv just like any other python package:

```
virtualenv updated-ipython
source ./updated-ipython/bin/activate
pip install ipython[all]
```
As long as it is activated, the `ipython` command *should* refer to IPython 3.0 which will be installed from Pip by default. Then, after you `cabal install` IHaskell from `master`, run `ihaskell install` and then `ipython notebook` in order to open the Jupyter terminal. You can then open notebooks or make new notebooks as usual, save for the fact that `New Notebook` is a drop down with multiple options now.

Notes:
- If you have your own IPython 2.0 profiles and such, note that you may want to back up `~/.ipython` (or whatever `ipython locate` tells you), as IPython will always use the same ipython dir.
- If you open a notebook in IPython 3.0 it gets upgraded to the new format, and is then no longer openable with IPython 2.0. So if that is an issue you may want to  make a copy of your notebook or make a new one.
- That said, IPython 3.0 is production-ready and out of beta and is now the standard distribution, so unless you have a particular reason to continue using 2.0, you may as well switch :)

**Comment by DougBurke** [comment]
My initial test seems to suggest that it is now fixed, but I want to do more testing (i.e. go back to the old version of IHaskell and make sure that what I've entered errors out there!).

**Comment by DougBurke** [comment]
I can confirm that with the GitHub version of IHaskell I don't see the Show instance problem.

Released version of IHaskell (with problem): http://nbviewer.ipython.org/gist/DougBurke/1d816955f7172c6c04b2

GitHub (fixed): http://nbviewer.ipython.org/gist/DougBurke/04a7fc91f18b321845f7
