### ISSUE TITLE
Flags cannot contain spaces

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#371]
Flags cannot contain spaces and arguments, leading to something like

```haskell
:set -package ghc-paths
```

which works fine in GHCi, to fail.

**Comment by gibiansky** [comment]
We currently use [`parseDynamicFlagsCmdline`](https://www.haskell.org/platform/doc/2013.2.0.0/ghc-api/src/DynFlags.html#parseDynamicFlagsCmdLine) for parsing flags in `Utils`, which should be fine. The issue is in `Evaluate.hs:469`, where we only pass the first flag to `Util.setFlags`.

This issue happens because we allow setting things that aren't GHC flags via `set`, such as `+t`. We should maintain this for compatibility with GHCi. Looks like we need a smarter parsing algorithm though -- perhaps just extract all the special non-GHC flags from the list of flags, then pass the rest to `setFlags`.

**Comment by gibiansky** [comment]
Fixed in #431, though `package` flag not yet supported
