### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#373]
On Mac,

```
brew install gcc48
cabal install cairo --with-gcc=gcc-4.8
```
may work but I'm using gcc49 (and I'm using Yosemite, not Mavericks).

More generally, I was thinking of maybe writing a full-blown installation script of IHaskell into a sandbox for Mac. Would there be interest in such a contribution?

**Comment by gibiansky** [comment]
I would have no issue with including such a script in the repo and adding some info about it to the README.

**Comment by FranklinChen** [comment]
It turns out that no special instructions now are needed for cairo installation. By the way, I have a completely automated Mac installation script that I was about to contribute, till news of the Jupyter merge came, so I'm trying to verify that it works with master now.

**Comment by gibiansky** [comment]
Great! Very good to hear.

The Jupyter merge should not affect the installation script too seriously, but let me know if you have any issues. 

I'm noting that documentation issue and others [here](https://github.com/gibiansky/IHaskell/issues/410); given the large amount of recent changes the documentation needs a significant update, and I'd like to collect all of that in one place so that I know I haven't missed anything when that happens.
