### ISSUE TITLE
Error message complains about binding, when function has a problem

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#386]
When writing a function that doesn't compile, the error message complains about the type binding.

![screen shot 2015-02-27 at 17 04 29](https://cloud.githubusercontent.com/assets/61575/6422118/cf96271c-bea2-11e4-9fe7-b351d5acec24.png)

I have to remove the type statement to see the actual error. When pasting exactly this text into a file and compiling with ghc, the correct error is shown:

```haskell
[1 of 1] Compiling Main             ( /tmp/test.hs, /tmp/test.o )

/tmp/test.hs:6:5:
    parse error (possibly incorrect indentation or mismatched brackets)
```

---

![screen shot 2015-02-27 at 17 06 34](https://cloud.githubusercontent.com/assets/61575/6422136/09d1e966-bea3-11e4-84e6-c6818fdd6e2e.png)

**Comment by gibiansky** [comment]
I've also run into this. Here is why it happens:

1. The parser breaks up the input into declarations using spacing.
2. Normally, the parser sees two declarations, a type declaration and a function declaration.
3. Since the type declaration is actually part of the function declaration, it joins them -- it knows to do this because type declarations above function declarations are allowed. It then executes them both at once.

In this case, though, the function has a parse error. Thus, the parser sees a valid type declaration and an unparseable block. It tries to run these in order. The first declaration is only a type declaration, and thus yields an error. IHaskell stops at the first error, thus only showing that one, instead of the parse error.

A potential fix would be to display all parse errors *always*, regardless of other errors. This might be a little confusing but at least the parse error message would show up.

**Comment by houshuang** [comment]
I think showing all errors would be useful. Would like to see examples
where that is really not helpful.

On Fri, Feb 27, 2015 at 5:11 PM, Andrew Gibiansky <notifications@github.com>
wrote:

> I've also run into this. Here is why it happens:
>
>    1. The parser breaks up the input into declarations using spacing.
>    2. Normally, the parser sees two declarations, a type declaration and
>    a function declaration.
>    3. Since the type declaration is actually part of the function
>    declaration, it joins them -- it knows to do this because type declarations
>    above function declarations are allowed. It then executes them both at once.
>
> In this case, though, the function has a parse error. Thus, the parser
> sees a valid type declaration and an unparseable block. It tries to run
> these in order. The first declaration is only a type declaration, and thus
> yields an error. IHaskell stops at the first error, thus only showing that
> one, instead of the parse error.
>
> A potential fix would be to display all parse errors *always*, regardless
> of other errors. This might be a little confusing but at least the parse
> error message would show up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/386#issuecomment-76481934>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by gibiansky** [comment]
Evaluation stops after the first error. You do not want to keep evaluating once you've reached a broken state. 

That said it makes sense for all *parse errors* to be evaluated and shown.
