### ISSUE TITLE
"Dead kernel" after installing and runing "IHaskell notebook"

### ISSUE THREAD

**Issue by slon1024** [gibiansky/IHaskell#407]
There's problem with starting notebook after installing.
```
➜   IHaskell notebook
...
2015-03-06 11:28:44.750 [NotebookApp] Kernel started: 9cbc74df-e4e5-4a57-a947-3c6985797860
IHaskell: Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.IPython.Stdin’
Use -v to see a list of the files searched for.

2015-03-06 11:28:47.749 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 9cbc74df-e4e5-4a57-a947-3c6985797860 restarted
IHaskell: Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.IPython.Stdin’
Use -v to see a list of the files searched for.
```

I use OS X **10.9.4** 
```
➜ ghc --numeric-version
7.8.3
➜ cabal --version
cabal-install version 1.22.0.1
```

There's the same problem with console
```
IHaskell console
Using system-wide IPython.
IHaskell: Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.IPython.Stdin’
Use -v to see a list of the files searched for.
```

I installed the newest version IHaskell manually from this repo (https://github.com/gibiansky/IHaskell)
```
➜  IHaskell git:(master) ./build.sh
a ipython_config.py
a ipython_console_config.py
a ipython_notebook_config.py
a ipython_qtconsole_config.py
a static
a static/base
a static/custom
a static/custom/conceal
a static/custom/custom.css
a static/custom/custom.js
a static/custom/hide_input.js
a static/custom/conceal/conceal.js
a static/base/images
a static/base/images/ipynblogo.png
a templates
a templates/ihaskell-basic.tpl
a templates/ihaskell.tpl
a .profile_version
cleaning...
Resolving dependencies...
Configuring ipython-kernel-0.3.0.0...
Building ipython-kernel-0.3.0.0...
Installed ipython-kernel-0.3.0.0
Configuring ihaskell-0.5.0.0...
Building ihaskell-0.5.0.0...
Installed ihaskell-0.5.0.0
```
Can you advice me how to debug it?

**Comment by gibiansky** [comment]
I've seen this error occasionally and often solved it by `cabal install`-ing from the `ihaskell` directory again; I'm not totally sure what causes it.

Try doing `import IHaskell.Display` and `:m + IHaskell.IPython.Stdin` in `ghci`, does that work?

**Comment by slon1024** [comment]
I'm not sure what the problem was. I removed all dependent packages and reinstalled... it works :).
Thanks @gibiansky, I already :heart: :heart: :heart: IHaskell.

**Comment by gibiansky** [comment]
@slon1024 Good to hear that reinstalling worked; I've had the same experience. I think it has to do with `*.hi` files becoming somehow outdated, or perhaps not matching the versions between different installs or something.

**Comment by artuuge** [comment]
I have encountered a similar problem when running iHaskell in Jupyter. 
The "dead kernel" message which emerges on a startup seems to be related to
the fact that the pattern matching in the function 'replyTo' defined in main/Main.hs
is not exhaustive. The latter can be fixed by appending to the definition the following:

replyTo _ _ _ ks = liftIO $ do
  return (ks, SendNothing)

The compiler is going to issue a warning about the overlapping instances,
so these lines should be placed after all other partial definitions of 'replyTo'.

**Comment by sumitsahrawat** [comment]
Which version (of `ipython/jupyter`, `ihaskell` etc.) are you using? This issue seems to have been fixed a long time ago.

> The latter can be fixed by appending to the definition the following:
> 
> replyTo _ _ _ ks = liftIO $ do
> return (ks, SendNothing)

This also has some problems of it's own. A catch-all case removes errors about incomplete pattern matches, which are very helpful when, e.g. a new constructor is added to an argument. In the current state, any changes from the IPython side usually become "kernel died" errors, which might be intentional. @gibiansky would have more to say about this.

**Comment by artuuge** [comment]
You are right, I just haven't noticed the commit ceb3abdd5187c749374e69f3c56f8f5a480bc9ce (#569).
Sorry, it's clearly my mistake! It is great if the problem is not there. 

I have actually encountered the "dead kernel" message in the middle of August and had to fix it (I should have reported then). 
You can reproduce the effect taking cab4cfdf4b31f3ef7111089c75a9c3236734bd19 which corresponds to ihaskell-0.6.5.0.

Unfortunately, I haven't built the latest gibiansky/IHaskell commit yet (I run out of 6GB RAM compiling ihaskell-widgets). 

Anyway, assume that you have:

Arch Linux, kernel 4.2.1-1-ARCH
ncurses 6.0-3
zeromq 4.1.3-1
cairo-infinality-utimate 1.14.2-1
pango 1.36.8-1
blas 3.5.0-1
lapack 3.5.0-1 
python 3.4.3
ipython 4.0.0
ghc 7.10.1
firefox 41.0
cabal 1.22.2.0

I run the following sequence:
clone https://github.com/gibiansky/IHaskell.git,
checkout cab4cfdf4b31f3ef7111089c75a9c3236734bd19, 
append 'hmatrix >= 0.10 && <0.17' and 'diagrams-lib <= 1.3.0.3' to library/build-depends in ihaskell.cabal. 
After that I install everything in a cabal sandbox, execute 'cabal exec bash',
run 'jupyter notebook', launch firefox, and open a new Haskell notebook in Jupyter.
This leads to a dead kernel.
The shortest way to get rid of it is to make 'replyTo' in main/Main.hs total by appending
replyTo _ _ _ ks = liftIO $ do {return (ks, SendNothing)}

**Comment by sumitsahrawat** [comment]
Yup. `ihaskell-widgets` does give me a lot of pain when compiling (I run out of 8gb of ram). I added a workaround to the build script, which promptly skips building ihaskell-widgets :smile:.

```bash
git clone https://github.com/gibiansky/IHaskell.git
cd IHaskell
./build.sh all no-widgets
```

Surprisingly enough, ghc-7.8.4 on travis manages to build this under 3gb of ram. Just after a system upgrade (ghc-7.10.2 became available today, hurray !!), I did not need to do anything other that just run those commands.

**Comment by artuuge** [comment]
Thanks a lot for pointing this out.
I have now upgraded to ghc 7.10.2 and it does a much better job than 7.10.1!
I am able to compile the iHaskell commit 8104d98f7b733df6f993c4bb6138def874e2f79e in one shot.
My machine has 6Gb RAM and the compilation of ihaskell-widgets consumes around 80% of memory in its highest point. The variant with no-widgets option and then compiling the widgets separately works fine as well, of course.

There is a small typo in ihaskell-display/ihaskell-widgets/ihaskell-widgets.cabal.
In the library/build-depends section the upper bound for singletons is 2.0.0.0, while it should apparently be just 2.0: 

singletons >= 0.9.0 && <2.0

For some reason cabal (upgraded to 1.22.6.0) ignores the inequality "<2.0.0.0" and proceeds with an installation of the most recent version into my sandbox causing a long sequence of compilation errors for the widgets.The inequality "singletons <2.0" results in an installation of 1.1.2.1 what is just fine.

**Comment by sumitsahrawat** [comment]
@artuuge I suggest that you treat that as a bug in IHaskell and file an issue, and a PR if you're willing :wink:

**Comment by daqo** [comment]
I had the same problem. Running `cabal install` resolved it for me.
