### ISSUE TITLE
Setting up profile directory?

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#418]
I want to set up a public notebook server for a demo on Monday. I know how to do this with IPython by creating a profile with `ipython profile create demoserver` and then editing `~/.ipython/profile_demoserver/ipython_notebook_config.py` appropriately with

```python
c.NotebookApp.password = "stuff"
c.NotebookApp.certfile = "stuff"
c.NotebookApp.ip = "stuff"
c.NotebookApp.open_browser = False
c.NotebookApp.port = "stuff"
```
but I don't see a profile directory generated from IHaskell?

**Comment by FranklinChen** [comment]
Ah, OK, I looked at `src/IHaskell/IPython.hs` and see that `ipython` is simply being called with some hardcoded arguments. It would seem that `IHaskell` should simply accept and pass on all arguments, e.g. `--profile demoserver`. Also, why the hardcoded notebook directory? IPython's default is to serve the current directory.

**Comment by gibiansky** [comment]
@FranklinChen 

IHaskell no longer has a profile directory; this is how kernels were managed in IPython 2, but in IPython 3 / Jupyter kernels own a directory under ~/.ipython/kernels (or wherever your .ipython lives); this directory has a kernel.js and a kernelspec.json, and potentially some auxiliary files. Profiles are no longer generated for kernels, as kernels are considered a "sub-part" of Jupyter, rather than IPython being a backend for the kernels.

The notebook directory is configurable via `--serve` or `-s`, so you can invoke IHaskell with
```
ihaskell notebook --serve=/path/to/my/directory
```
or
```
ihaskell notebook -s .
```
for traditional `ipython notebook` behaviour. 

That said, `ihaskell notebook` is just an alias for
```
ipython notebook --notebook-dir=/the/default/ihaskell/notebook/directory
```

I personally prefer my invocations to be path independent; however I'm open to arguments for or against. Historically IHaskell has had its current behavior; if we revert to standard `ipython` behaviour then the `ihaskell notebook` command should likely be deleted, since then it would literally be a synonym for `ipython notebook`, which would be somewhat pointless.

I agree that passing along arguments may be a good idea; however, there are tons of IPython arguments, so it seems a bit silly to pass all of them along, given that IHaskell has to parse them anyways. So perhaps the better option is just to make it as clear as possible that `ihaskell notebook` is simply a wrapper for `ipython notebook --serve=~/.ihaskell/notebooks`, and then suggest that for more complex invocations, users should just use `ihaskell notebook` directly. 

So, options are:

1. Remove `ihaskell notebook` entirely, as it is just a synonym for `ipython notebook`.
2. Make it more clear that `ihaskell notebook` is a synonym for `ipython notebook --notebook-dir=~/.ihaskell/ipython`, and suggest to users that for more complex invocations they should use ipython directly.
3. Do nothing. 

Other notes:
- If we remove `ihaskell notebook`, then it seems that removing `ihaskell console` and `ihaskell convert` is also a good idea for symmetry. It would be strange otherwise, IMHO.  I think I would like to remove `ihaskell convert` regardless, as I believe reading new ipynb files is most likely broken. However, if we remove `ihaskell console`, then IHaskell can no longer serve as a replacement for GHCi. However, the potential of IHaskell as a ghci replacement is actually pretty big and recently gotten larger -- version 5 of the messaging spec allows the kernel to decide whether code is complete or not, so IHaskell could allow users to input multiline expressions and declarations into it without any weirdness (unlike ghci, though I guess there are ways to get around that). That said, IHaskell is slow to start up (sadly) and a little slow to respond, which makes it very mediocre as a GHCi replacement. 

In general, we can have one of two guiding principles:

- Make IHaskell-related  shortcuts easy and simply by providing terminal commands for them; this however masks the fact that they are effectively aliases for IPython commands.
- Do not duplicate functionality and tell users to use ipython commands entirely.

Thoughts from users? @houshuang @cje

**Comment by FranklinChen** [comment]
Thinking about this, I believe that IPython usage should now no longer be masked, both because of the importance of being able to do configurations anyway and because of consistency with instructions for other languages that have IPython kernels, such as Julia, R, Go, which call `ipython` explicitly.

Especially as the Jupyter name and infrastructure takes off, away from its original basis in Python, we'll want to emphasize that IHaskell is a kernel that is part of a larger ecosystem people may want to use. Embedding computations from multiple languages will, I think, be potentially a big draw.

**Comment by gibiansky** [comment]
See #428, which implements this change -- now IHaskell cmdline interface does not duplicate anything from IPython.
