### ISSUE TITLE
Contribute to try.jupyter.org?

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#452]
Get a Haskell example up for https://try.jupyter.org/ ?

**Comment by gibiansky** [comment]
[Good idea](https://github.com/jupyter/try.jupyter.org/issues/5)

**Comment by gibiansky** [comment]
Looks like a modification of the Docker notebook in this repo would probably work.

**Comment by sumitsahrawat** [comment]
It's currently in the works. The only issue is the large install size of GHC + IHaskell.

Take a look at jupyter/docker-demo-images#29

**Comment by gibiansky** [comment]
Take a look at my comment on that thread for how to reduce filesize. Let me know if you have issues after trying some of the suggestions I had; if so I'll go ahead and download the image and play around with it :)

Glad to hear this is pretty close!

If this gets merged, I might suggest to @chrisdone to include a link to try.jupyter.org somewhere on haskell.org; it might be the easiest way to try out Haskell by far. (Might give a strange first impression, since IHaskell isn't quite Haskell, but it would be worth discussing anyways.)

**Comment by sumitsahrawat** [comment]
@gibiansky Are there any issues you would like resolved before making a new release. That release might be used for docker too, so it can be polished accordingly.

**Comment by gibiansky** [comment]
@sumitsahrawat No, none of the issues are pressing enough right now to delay making a new release.  I can make a Hackage release as necessary – let me know. One should definitely be made soon to add GHC 7.10 support to Hackage IHaskell.

**Comment by sumitsahrawat** [comment]
It'd be good to have a release as soon as possible.
Take a look: https://github.com/jupyter/docker-demo-images/pull/29#discussion_r29996689.
Everybody would love to have 7.10 support on hackage too.

**Comment by gibiansky** [comment]
No problem. I'll try to make one today or tomorrow.

**Comment by sumitsahrawat** [comment]
IHaskell is now a part of `jupyter/demo`. The site updates itself continuously when it's under less load, and IHaskell will eventually become visible online.

**Comment by sumitsahrawat** [comment]
Check it out https://try.jupyter.org/ :sparkles:

**Comment by gibiansky** [comment]
@sumitsahrawat Awesome!!! I posted it on [reddit](http://www.reddit.com/r/haskell/comments/376aqh/ihaskell_on_tryjupyterorg/) to brag about how great this is.
