### ISSUE TITLE
Changing and re-evaluating a data type does not change its type.

### ISSUE THREAD

**Issue by sbrother** [gibiansky/IHaskell#467]
To reproduce:
1. Enter `data X = A Int | B String` into a cell and run it.
2. `:t A` will return `A :: Int -> X`
3. Edit the cell containing the data declaration to say `data X = A Float | B String`, and re-run it.
4. `:t A` should return `A :: Float -> X` (and does if you repeat this exercise in GHCi). Instead it is still `A :: Int -> X`

**Comment by gibiansky** [comment]
Is this on GHC 7.6? There were a few problems with this pre-7.8, but it should be fixed on 7.8 and above.

IHaskell supports 7.6.3 but only somewhat – a lot of bugs in GHC were fixed in 7.8 and even more in 7.10 that are necessary for IHaskell to function properly.

(I am having a hard time reproducing this on 7.8, that is, it seems to work. If this is a 7.6 issue then it probably won't get fixed, but if this is a newer GHC then I might need some help reproducing it...)

**Comment by sbrother** [comment]
Yep - it looks like the version of Haskell Platform that I gets installed when you `apt-get install haskell-platform` in Ubuntu 14.04 is unfortunately 2013.2.0.0 which contains GHC 7.6.3. I just removed that and installed Haskell Platform 2014.2.0.0 (which includes GHC 7.8) and everything works perfectly. The previous bug (#466) is also fixed. 

It may be worth mentioning in the README.md that IHaskell notebook won't work correctly with the default Haskell Platform from Ubuntu. Not IHaskell's fault -- Ubuntu shouldn't be shipping an archaic version of haskell-platform -- but mentioning it could save a lot of frustration from newbies like myself!
