### ISSUE TITLE
The type signature for ‘minBound’ lacks an accompanying binding  (The type signature must be given where ‘minBound’ is declared)

### ISSUE THREAD

**Issue by sindhus** [gibiansky/IHaskell#509]
hi! I am trying out code examples from "Learn you Haskell" book and am in "Types and Typeclasses" chapter where 'Bounded' typeclass is being explained. I tried `minBound :: Int` to see what is the minimum Integer number my machine is capable of and I get:

"The type signature for ‘minBound’ lacks an accompanying binding  (The type signature must be given where ‘minBound’ is declared)"

What am I doing wrong?
Am using Haskell kernel through ipython notebook UI. Thanks!

**Comment by gibiansky** [comment]
This is a downside of IHaskell, maybe a bug, but one I don't have a good way of fixing.

`maxBound :: Int` is ambiguous: you could be providing a type signature as a declaration, or it could be an expression. If you write `(maxBound :: Int)` instead, with parentheses, then it will clearly be an expression. 

I'm going to leave this open because it's a place where a better error message could exist. For example if could just assume that type signatures without bindings are actually expressions.

**Comment by ijustwannanamewhyitissodifficult** [comment]
Looks like this was closed? any later progress?

**Comment by vaibhavsagar** [comment]
Not that I'm aware of. Please use `(minBound :: Int)` as suggested.
