### ISSUE TITLE
IHaskell isn't respecting "--ghclib" argument

### ISSUE THREAD

**Issue by thomasjm** [gibiansky/IHaskell#570]
I have a global stack config with a resolver that specifies GHC 7.8.4. However, IHaskell's stack.yaml file causes it to be build with GHC 7.10.2. This means that when I run e.g. `ihaskell kernel {connection_file}` within the cloned IHaskell project folder, it works. But if I run it outside that folder (for example, the way the `kernel.json` connection file specifies) then I get an error. I put a bunch of `putStrLn`s in IHaskell and determined that this happens close to the `runGHC` command in `Evaluate.hs`.

```
Run from outside a project, using implicit global config
GOING TO SERVE PROFILE. libdir: "/Users/tomm/.stack/programs/x86_64-osx/ghc-7.10.2/lib/ghc-7.10.2"
Heartbeat port: 56291
Did runGhc with this libdir: "/Users/tomm/.stack/programs/x86_64-osx/ghc-7.10.2/lib/ghc-7.10.2"
Sandbox packages: Nothing
About to getSessionDynFlags
Just did getSessionDynFlags
ihaskell: /Users/tomm/.stack/programs/x86_64-osx/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not a ghc-pkg db file, wrong file magic number)
```

For reference, here's how `kernel.json` is telling IPython to invoke the kernel: 

```
{"display_name":"Haskell","argv":["/Users/tomm/.local/bin/ihaskell","kernel","{connection_file}","--ghclib","/Users/tomm/.stack/programs/x86_64-osx/ghc-7.10.2/lib/ghc-7.10.2"],"language":"haskell"}
```

**Comment by gibiansky** [comment]
This is on purpose – IHaskell uses whatever config is provided by stack at the current directory it's run in. 

That said, it is confusing with the `--ghclib` argument... 

Without doing this, IHaskell would forever be locked to the resolver it uses. If you wanted to use it to help develop another project in another resolver, you would be unable to.

The downside is that if you use it outside the ihaskell directory, you have to install the ihaskell support display libraries in whatever snapshot you're running it in.

**Comment by thomasjm** [comment]
Not sure I understand what you mean by "help develop another project in another resolver." The way I see it, the purpose of the installed `ihaskell` binary is to be used as a kernel by Jupyter console, notebook, etc. So it should work when invoked with a command like `ihaskell notebook`, no matter what  directory you're in when you type the command. That's what the intent of the `--ghclib` argument in `kernel.json` appears to be. 

(I don't think this particular problem has anything to do with the support display libraries being installed or not; I'm not even getting to that point because it's trying to use an incompatible GHC package database.)

**Comment by gibiansky** [comment]
This is a tricky issue.

For example: I am developing some project `A`. It involves a bunch of packages that I want to work with. So I have a Stack snapshot and `stack.yaml` in directory `A`. 

I install IHaskell. IHaskell comes with a `stack.yaml`, so to install it I use a separate Stack snapshot. Now I have two snapshots. If IHaskell is unaware of Stack, it will *always* use the IHaskell snapshot. There will be no way to use the packages related to `A` in IHaskell.

What exists right now is an attempt to fix this issue: if IHaskell is run somewhere where there is a `stack.yaml`, it will use `stack` to initialize it's environment, as if it is being run with `stack exec ihaskell`. 

We still call `runGhc` with the `libdir` specified on the command line.

In your case, it seems like the issue is that there are multiple GHC versions in play. I haven't really encountered this before, which should explain why it failed; it was simply unforeseen. 

The issue may actually be the opposite of what you are saying. We *do* respect the libdir specified on the command line, but this is a problem, because the libdir is GHC 7.10.2 whereas the environment is GHC 7.8. Perhaps if the libdir *also* specified GHC 7.8 it would work. Can you try that? Switch the libdir flag in `kernel.json` to specify the GHC 7.8 libdir.

If that indeed fixes things, then we can expand from just querying stack for the environment to also using stack to figure out a proper libdir.

**Comment by gibiansky** [comment]
This is now behind the `--stack` flag. The behaviour described above is no longer the default.
