### ISSUE TITLE
Break out Stdin processing to its own package

### ISSUE THREAD

**Issue by alanz** [gibiansky/IHaskell#608]
The process of wrapping the stdin for ghci is useful, and I would like to use it for the [ghci-ng plugin for haskell-ide-engine](https://github.com/alanz/haskell-ide-engine/tree/ghci-ng/hie-ghci-ng)

I can either copy and amend the code, or break it out into a separate package.

What is best?

**Comment by gibiansky** [comment]
I would be happy with either solution. The code you're looking for is in `src/IHaskell/IPython/Stdin.hs`. It probably won't just be a simple copy/paste b/c this depends heavily on IPython-specific stuff.

Let me know if you have any questions.

**Comment by alanz** [comment]
I assume this does a global swap-out of stdin. In other words, once this is in place anything that does stdio in the running process will be routed through these pipes.

Which would obviously mean that any other protocol making use of stdio would be unable to run, or would get strange results.

**Comment by gibiansky** [comment]
Hmmm... I am not sure of that, actually, for two reasons.

First of all, it does a swap out of stdin in the interpreted context, not the compiled one. These probably share the raw file handles at the lowest level, but use different `Handle` values. So I'm not sure how it interacts with the compiled code's stdin. But my best guess is that it applies to the compiled code as well, so you would be right.

Also, either way, you could undo the change. In Ihaskell, we have to do the same thing to stdout in order to capture GHCi output. However, unlike witih stdin, we swap out stdout every time we need to run something, and then swap it back immediately afterwards. The same should be possible with stdin, although since there's a thread running to feed stdin, you would also need to clean up this thread.

**Comment by alanz** [comment]
Ok
