### ISSUE TITLE
several display matters

### ISSUE THREAD

**Issue by lmoss** [gibiansky/IHaskell#752]
I'm getting started with iHaskell and have a few issues with displays of various sorts. 

First, in the example notebook Conjugate Gradient.ipynb, it's clear that the LaTeX definition in the first paragraph is messed up.  That is, the \newcommand in the markdown didn't work out.   Have there been changes to the way LaTeX works in markdown cells?

Second, how does one include LaTeX style files for definitions in markdown cells?  I don't see examples in any of the files.

Speaking of examples, the package IHaskell.Diagrams isn't well-documented.   Is there stuff that's not on the web that I can look at?   I'm having trouble finding much of anything.

**Comment by leftaroundabout** [comment]
I don't think IHaskell has anything whatsoever to do with LaTeX formulas in Markdown cells, that's purely a Jupyter / MathJax issue. I suppose what you mean is the way said notebook looks when you view it directly on [Github](https://github.com/gibiansky/IHaskell/blob/master/notebooks/Conjugate%20Gradient.ipynb). The reason for this is evidently that Github does _not_ embed MathJax, instead it pre-renders all formulas to images on the server side – but that means `newcommand` doesn't work. But if you view the notebook eg [through nbviewer](http://nbviewer.jupyter.org/github/gibiansky/IHaskell/blob/master/notebooks/Conjugate%20Gradient.ipynb), this problem doesn't arise.

Reg. your question about LaTeX style files... frankly, I'd forget it. Embedded MathJax is good for simple formulas in standard AMSMath-LaTeX. For anything more complicated TeX-wise, Jupyter notebooks aren't really suited. You don't get to control much about the document layout etc. from LaTeX anyway... if you want that, why not write a _LaTeX document_?

If the reason for your question is more that you find standard AMSMath too awkward for typing the formulas you need, and want to include style files that just make the formulas you need feasible to type, I'd see your point. I do think it's possible `\usepackage`s, but at any rate you will run into the problem that the notebooks won't render properly in Github's previewer. Perhaps that wouldn't really be a problem at all for you.
At any rate, as I said, this has nothing to do with IHaskell – ask the Jupyter folks.

There is an alternative you could consider though, namely, generating the formulas _from Haskell code_, rather than manyally typing any LaTeX. That can be done through the `ihaskell-hatex` interface. A Haskell eDSL can in principle to a much better job for formulas than raw LaTeX; check out the [TeX-my-math package](https://github.com/leftaroundabout/Symbolic-math-HaTeX/blob/master/EXAMPLES.md).

Reg. documentation for IHaskell-diagrams... there's not much that could be documented there. Just define diagrams as explained in e.g. [the diagrams manual](https://archives.haskell.org/projects.haskell.org/diagrams/doc/manual.html). Choose the Cairo backend. The thus defined diagrams can then be displayed in IHaskell cells.

**Comment by lmoss** [comment]
Hi -- thanks very much!   
I hadn't known about Jupyter and MathJax, so you set me straight.
My main interest in this issue with LaTeX is that I have a few macros that I'd like to use.  Style files would also be great.   I know that I could get by without these, but having them would make life easier.  I haven't been able to use \usepackage, at least not so far.   I could ask over at Jupyter.  

ihaskell-hatex looks interesting, but it's not needed for what I'm doing.

And on diagrams: ok, I'll rtfm.   But since I'm talking to you, I have similar questions about charts and about pretty-printed tables.   Any suggestions on those?  I'll try with the cairo-backend first.   I see very little out there in the way of slow documentation.

**Comment by vaibhavsagar** [comment]
Have a look at https://ocharles.org.uk/blog/posts/2013-12-24-24-days-of-hackage-charts.html and/or ask over at https://github.com/timbod7/haskell-chart :smiley:

**Comment by lmoss** [comment]
Thanks, I'll do that.   
Meanwhile, I also see IHaskell.Tables.Data, and that's also of immediate interest.   
Thanks again to you both.

**Comment by vaibhavsagar** [comment]
Great, closing this.
