### ISSUE TITLE
Question: Why not use GHCi?

### ISSUE THREAD

**Issue by dabro** [gibiansky/IHaskell#767]
IHaskell is awesome.  I was trying to understand it's capabilities and limitations, and started wondering why IHaskell hooks directly to the GHC api and not through GHCi or a modified GHCi?  It seems like IHaskell is a custom GHCi.  There were obviously clear design decisions early in this project that led to the current approach -- would you be willing to share what they were?  Or a link to where this is already discussed?

As an example, FP Complete took GHCi and modified it to support their Emacs haskell-mode Intero plugin.

The most obvious advantage would be access to all the `:xxx` functionality, eg incremental compilation,`:set args` and debug functionality.  I have no idea what the downsides would be.

Absent a customized GHCi, the Emacs `dante` and `interactive-haskell-mode` plugins interact directly with GHCi.  The downside of this approach is a brittle, stringly-typed api.  Excepting that, it seems like a thin shim between Jupyter and GHCi would work?

**Comment by vaibhavsagar** [comment]
Good question! I don't know enough about the history of IHaskell to answer this, but I can make a few points:

- As far as I can tell, GHCi does not have an friendly API, and based on a cursory skim of [`GhciMonad.hs`](https://github.com/commercialhaskell/intero/blob/55b17bc6b9cf1e8621a210fd07de6177e55d1334/src/GhciMonad.hs), Intero has its own wrapper around the GHC API and the small API GHCi does provide. For example, Intero's [statement execution](https://github.com/commercialhaskell/intero/blob/55b17bc6b9cf1e8621a210fd07de6177e55d1334/src/GhciMonad.hs#L302-L326) uses the GHC API directly, and I don't think we'd be able to do it differently.
- `GHCi` has only supported `let`-less variable bindings since 8.0, so our shim would probably have had to parse the language and insert `let`s to use straight GHCi.
- GHCi doesn't support inline module definitions like IHaskell does.
- GHCi doesn't support rich text output like `IHaskell.Display`.

Another approach suggested recently was switching to [`hint`](https://hackage.haskell.org/package/hint). I think it's telling that `hint` is also a wrapper around the GHC API instead of GHCi, and it doesn't support all of the features our current solution does (i.e. inline modules).

**Comment by vaibhavsagar** [comment]
Closing as not actionable.
