### ISSUE TITLE
`--notebook-dir` argument breaks `stack` isolation

### ISSUE THREAD

**Issue by mkeeter** [gibiansky/IHaskell#792]
After installing IHaskell per the README, I had a lot of trouble running it with the `notebook-dir` argument, e.g. `stack exec jupyter -- notebook --notebook-dir=~/code/notebooks`.  I cleaned all of the old Haskell stuff (cabal / stack / etc) from my machine, and it worked, but I notice a strange line in startup:

```
➜  IHaskell git:(master) stack exec jupyter -- notebook --notebook-dir=~/code/advent
[I 19:07:52.798 NotebookApp] The port 8888 is already in use, trying another port.
[I 19:07:52.809 NotebookApp] Serving notebooks from local directory: /Users/mkeeter/code/advent
[I 19:07:52.809 NotebookApp] 0 active kernels
[I 19:07:52.810 NotebookApp] The Jupyter Notebook is running at:
[I 19:07:52.810 NotebookApp] http://localhost:8889/?token=cfedc6ffc567cbf503b32fff947a630f65817c86a108ef22
[I 19:07:52.810 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:07:52.813 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=cfedc6ffc567cbf503b32fff947a630f65817c86a108ef22
[I 19:07:53.258 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 19:07:57.283 NotebookApp] Kernel started: ff0d322f-aa61-409a-aa57-d3aab018eac3
[W 19:07:57.299 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20171204190752 (::1) 9.44ms referer=http://localhost:8889/notebooks/2017/Day%205.ipynb
[W 19:07:57.375 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20171204190752 (::1) 2.29ms referer=http://localhost:8889/notebooks/2017/Day%205.ipynb
Writing implicit global project config file to: /Users/mkeeter/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-9.17
Downloading lts-9.17 build plan ...
Downloaded lts-9.17 build plan.
```

It seems like using a custom notebook directory causes `stack` to fall back to the global project, which is why it was failing for me before (because my global project was configured as an older version of GHC).

Is there a way to pass the `--notebook-dir` argument while still keeping `stack`'s isolation?

**Comment by vaibhavsagar** [comment]
I'm not aware of a way to pass `--notebook-dir` and also use the `stack.yaml` of IHaskell's build directory. If I can suggest an alternative workflow:

1. Set up your notebook directory as a Stack project with your preferred resolver:
```bash
$ stack init <notebook-dir>
```
2. Launch IHaskell from your notebook directory:
```bash
$ cd <notebook-dir>
$ stack exec -- jupyter notebook
```

This will use the `stack.yaml` of your notebook directory, and should be free of issues as long as your resolver and your build of IHaskell use the same version of GHC. An advantage of this approach is that you can add additional packages to the `.cabal` file that `stack init` generates, run `stack build`, and then use those packages in IHaskell. This is what I did for AoC [last year](https://github.com/vaibhavsagar/advent-of-code/tree/36fd476fada496bf31c1633df51086b20a58d050/2016), which it looks like you're also using IHaskell for :smile:.

If you want even more isolation, I'd suggest checking out the Nix approach, which I personally use and love. Here's an example of my [advent of code directory](https://github.com/vaibhavsagar/advent-of-code/tree/36fd476fada496bf31c1633df51086b20a58d050/2017) for this year. I use this as follows:

```
$ cd ~/code/advent-of-code/2017
$ nix-build
$ result/bin/ihaskell-notebook
```
and it launches a fully-configured IHaskell environment with the additional packages that I have configured. I especially like this because I'm using three different laptops this year and I can have an identically-configured IHaskell environment on all of them just by synchronising my repository and running `nix-build`.

Hope this helps!

**Comment by vaibhavsagar** [comment]
Closing this.
