### ISSUE TITLE
Make images user-resizable

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#81]
The Python IPython kernel adds the class ui-resizable to images, which means that the user can resize them in the browser (works in latest Chrome), would be nice to have this in IHaskell too.

**Comment by silky** [comment]
this doesn't work for me.

the image i'm generating is a chart that is a `Renderable a`, so i'm reading here - https://github.com/gibiansky/IHaskell/blob/master/ihaskell-display/ihaskell-charts/IHaskell/Display/Charts.hs

the problem is that for me the img src says that it is a `data:image/svg+xml...` whereas to be resizable it should be png

how can i force it to be png?

**Comment by silky** [comment]
hmm, i found this - https://github.com/gibiansky/IHaskell/wiki#opt-no-svg - which makes it display a png instead; but the png isn't resizable!
