### ISSUE TITLE
Launch from inside IHaskell folder?!

### ISSUE THREAD

**Issue by capn-freako** [gibiansky/IHaskell#810]
The _Running_ section of _README.md_ says to launch like this:

`stack exec jupyter -- notebook`
`
I assume that means I should be inside the _IHaskell_ folder when I execute the above command.
Is that correct?
And, if so, doesn't it mean that I'll be confined to that folder and its children, when opening and/or creating notebooks? That seems a little restrictive.

**Comment by vaibhavsagar** [comment]
> I assume that means I should be inside the IHaskell folder when I execute the above command.
Is that correct?

After you run `ihaskell install`, you can run the above command from any folder :smiley:. The purpose of the `stack exec` is to bring the appropriate GHC and other Haskell tools onto the `$PATH` and set other environment variables such as `$GHC_PACKAGE_PATH` appropriately, but if you for some reason wanted to do that manually you could just run `jupyter notebook` and this would work too.

My preferred workflow is to run in from within another Stack project because this makes the packages from that project available to any IHaskell notebooks started in this manner. For more details see https://github.com/gibiansky/IHaskell/issues/792#issuecomment-349186483.

**Comment by capn-freako** [comment]
Ah, I get it now. Thanks!
