### ISSUE TITLE
Kernel Dies -- inappropriate type

### ISSUE THREAD

**Issue by z01db3rg** [gibiansky/IHaskell#815]
I'm runnig IHaskell on different machines and never had problems before, but since I moved to Arch Linux and installed IHaskell the Kernel dies stating:
`[W 20:11:43.298 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20180201201124 (127.0.0.1) 3.28ms referer=http://localhost:8888/notebooks/functional_programming/haskell/Craft/exercises/chapter2.ipynb
ihaskell: /home/zoidberg/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.2.2/lib/ghc-8.2.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
`
On another machine with the very same OS-Setup it worked until last week.

**Comment by vaibhavsagar** [comment]
I suspect that either your `~/.stack/global-project/stack.yaml` or the `stack.yaml` you used to install IHaskell incorrectly refers to an `LTS-9` resolver, as per https://github.com/gibiansky/IHaskell/issues/804 and https://github.com/gibiansky/IHaskell#the-kernel-keeps-dying-ihaskell--stack. Please have a look and, if it turns out I'm wrong and something else is going on, let me know.

**Comment by z01db3rg** [comment]
Both yaml files are set to the LTS-10.4 resolver, which is my current stack resolver.

**Comment by vaibhavsagar** [comment]
I don't understand, where does `stack install cabal-install` come into play? Which steps are you using to install IHaskell?

**Comment by vaibhavsagar** [comment]
Closing.
