### ISSUE TITLE
Cannot compile because of zlib version, missing libtinfow.so.6

### ISSUE THREAD

**Issue by jordana309** [gibiansky/IHaskell#858]
I'm following the instructions you have posted in the readme, but when I get to stack install --fast, I can't compile everything because of the following error:

```
While building custom Setup.hs for package Chart-cairo-1.8.3 using:
      /home/jordan/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/jordan/Codes/src/IHaskell/.stack-work/logs/Chart-cairo-1.8.3.log
    Configuring Chart-cairo-1.8.3...
    Preprocessing library for Chart-cairo-1.8.3..
    Building library for Chart-cairo-1.8.3..
    [1 of 1] Compiling Graphics.Rendering.Chart.Backend.Cairo ( Graphics/Rendering/Chart/Backend/Cairo.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/Graphics/Rendering/Chart/Backend/Cairo.o )
    <command line>: can't load .so/.DLL for: /home/jordan/Codes/Anaconda/lib/libcairo.so (/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/jordan/Codes/Anaconda/lib/./libpng16.so.16))
```

How can I fix this? I tried to get a previous version, but that broke some other packages that I use.

Thanks!

**Comment by vaibhavsagar** [comment]
This looks like an issue with your `libcairo` install. Try upgrading that and see if it makes a difference. If it doesn't, try commenting out `./ihaskell-display/ihaskell-charts` under `packages` in `stack.yaml` (and possibly every other `ihaskell-display` module) and see if that resolves the issue.

**Comment by jordana309** [comment]
That's...rather unsatisfying. I ran stack install --fast several times, and got to where only 4 packages would no longer compile. I then commented out charts and display, and it finished fine. But then I found that when I tried to ihaskell install ---stack, then I'm told that "libtinfow.so.6: cannot open shared object file: No such file or directory". I tried to update ncurses to the newest version, and I can't find any other package with that library. Thoughts?

**Comment by vaibhavsagar** [comment]
You are aware that this is an issue with your system dependencies and not with IHaskell, right? I agree that it is unsatisfying when you can't run one command and have everything work reliably, and that's why we support [installing with Nix](https://github.com/gibiansky/IHaskell#nix), which is my preferred way of using IHaskell.

**Comment by jordana309** [comment]
Yes, I know it's my system. I installed a code that messed with all my compilers, and it's been causing me problems ever since. Though I'm not sure why the python libraries would be messed up. I am rather new to Linux and building things from source, so I know that I have and will make many mistakes. I didn't mean that comment to be an attack or dig.

What are your thoughts about libtinfow.so.6? Or should I abandon this just use Nix? Looking over that link, it appears to create a new python environment that just has IHaskell in t, is that right?

**Comment by vaibhavsagar** [comment]
I think I have seen that `libtinfow.so.6` error before, and IIRC after upgrading `ncurses` I ran `stack setup` which downloaded and installed a different version of GHC. Have you tried this? I allude to it [here](http://vaibhavsagar.com/blog/2018/03/17/faking-non-nixos-stack/) very briefly.

I would definitely recommend installing Nix if your primary aim is to try IHaskell because it's self-contained and I have much higher confidence that the instructions I've provided will work. If you're more interested in setting up Stack then I have to wonder why you're asking here instead of the `#haskell` IRC channel or somewhere similar. The Nix method will create a symlink called `result` that will allow you to run IHaskell by executing `result/bin/ihaskell-notebook`. There's no changing of environments but it doesn't add what's needed for IHaskell to your environment either, because you can delete that symlink and everything will go back to the way it was before (from the perspective of your system).

If you have a quick look through the issue tracker you'll see that a lot of people have issues with this aspect of running IHaskell on Stack, because we have a lot of system dependencies and Stack doesn't manage those at all (as I'm sure you've noticed). It is a bit frustrating seeing people have the same kinds of issues over and over again when I don't have any control over over their systems and we do have a more robust solution available that nobody seems to want to try :smile:.

**Comment by vaibhavsagar** [comment]
May I close this issue?

**Comment by jordana309** [comment]
Yes. Sorry - things got crazy for me for a while. I appreciate your help.
This issue can for sure be closed.

**Comment by vaibhavsagar** [comment]
Thanks!
