### ISSUE TITLE
"ihaskell_jupyterlab" and "jupyterlab-ihaskell" both on npm, neither match the name of the package in the docs

### ISSUE THREAD

**Issue by cemulate** [gibiansky/IHaskell#936]
Which one is the maintained package? Depending on the answer, the docs should be updated to reflect the correct package name.

https://www.npmjs.com/package/ihaskell_jupyterlab
https://www.npmjs.com/package/jupyterlab-ihaskell

Currently, the docs say:

```
jupyter labextension install ihaskell_labextension
```

**Comment by MMesch** [comment]
agree.

The new package is `jupyterlab-ihaskell` but it is currently not usable because of an incompatibility of ihaskell with jupyterlab >= 0.34 . It is identified but needs fixing. PRs are welcome, I won't have time in the coming month or so:
 https://github.com/gibiansky/IHaskell/issues/912

the old one `ihaskell_labextension` works for jupyterlab < 0.34

The README should be updated accordingly.

Sorry about this inconvenience, feel free to submit PRs to make this more consistent.

**Comment by cemulate** [comment]
Ah, I see - thanks for the explanation! The old extension is working for me in the mean time.
