### ISSUE TITLE
mismatched interface file versions (wanted "8044", got "8063")

### ISSUE THREAD

**Issue by octonion** [gibiansky/IHaskell#986]
I followed the instructions to install on Ubuntu 18.04 and it went fine, but upon creating my first Haskell notebook it automatically installed ghc 8.6.3 (!) and now I'm getting the above error. Note that ghc 8.4.4 is still installed in ~/.stack alonside 8.6.3. I see mention of this issue at the bottom of the installation guide, but it's not clear how to correct it.

**Comment by vaibhavsagar** [comment]
Where did you create your first IHaskell notebook? I think what happened is that IHaskell runs

```
stack exec -- env
```

as part of its Stack support, and this probably downloaded and installed `lts-13.0` because it was run outside a Stack project. If you want to continue using IHaskell with GHC 8.4.4, I would suggest only running IHaskell inside a Stack project with `lts-12.*`. Alternatively, IHaskell does support GHC 8.6 so you can instead

1. Update the resolver in `stack-8.6.yaml` to `lts-13.0`.
2. Replace `stack.yaml` with `stack-8.6.yaml`
3. Reinstall IHaskell, which will now expect 8.6.
4. Edit your `~/.stack/global-project/stack.yaml` to reference `lts-13.0`.

I would suggest the first approach, because not all of the IHaskell display packages work on GHC 8.6 yet.

**Comment by Joe-a-d** [comment]
Hey @vaibhavsagar I have the same problem. I followed your instructions, changed the resolver in `stack-8.6.yaml` to `lts-13.0` and renamed it as `stack.yaml`. Then I ran ` stack install --fast` and 
`ihaskell install --stack` again, and I still get the mismatch error. 

I have also attempted to add `resolver: lts-13.0` to the `config.yaml`but I get this warning message: 

> .stack/config.yaml: Unrecognized field in ConfigMonoid: resolver

What do you mean by this?
> I would suggest only running IHaskell inside a Stack project with lts-12.*

I ran `stack exec jupyter -- notebook` from within the IHaskell sample notebooks directory

**Comment by Joe-a-d** [comment]
SOLVED: 

Changed the `stack-8.6.yaml` inside both `~/IHaskell`  and `~/IHaskell/IHaskell`
